server:
  port: 8888



application:
  file-save-location: ~/text-generator/vm

spring:
  datasource:
    #url: jdbc:h2:./db
    #driver-class-name: org.h2.Driver
    hikari:
      username: root
      password: root
      jdbc-url: jdbc:mysql://127.0.0.1:3306/txtgen
      driver-class-name: com.mysql.cj.jdbc.Driver
      minimum-idle: 1
      maximum-pool-size: 2
      connection-test-query: select 1
  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true